spring:
  datasource:
    url: jdbc:postgresql://${DEMO_DB_HOST}:${DEMO_DB_PORT}/${DEMO_DB_NAME}
    username: ${DEMO_DB_USERNAME}
    password: ${DEMO_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  logging:
    level:
      org:
        springframework:
          security: debug
