version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=${DEMO_DB_USERNAME}
      - POSTGRES_PASSWORD=${DEMO_DB_PASSWORD}
      - POSTGRES_DB=${DEMO_DB_NAME}
    ports:
      - '${DEMO_DB_PORT}:5432'